services:
  postgres:
    build:
      context: postgres/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=studs
      - POSTGRES_USER=muzika
      - POSTGRES_PASSWORD=tchaikovsky
    networks:
      - postgres
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=muzika
      - MINIO_ROOT_PASSWORD=tchaikovsky
    command: server --console-address ":9001" /data
    networks:
      - minio
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: muzika
      MINIO_ROOT_PASSWORD: tchaikovsky
      DEFAULT_BUCKET_NAME: imports
    entrypoint: >
      /bin/sh -c "
            until (/usr/bin/mc config host add myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}) do echo '...waiting...' && sleep 1; done;
            /usr/bin/mc mb myminio/$${DEFAULT_BUCKET_NAME};
            /usr/bin/mc policy set download myminio/$${DEFAULT_BUCKET_NAME};
            exit 0;
            "
    networks:
      - minio
networks:
  postgres:
  minio: